POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "pontus@test.se",
  "password": "pontus"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "pontus@test.se",
    "password": "pontus"
}
### 
POST http://localhost:3000/api/auth/logout

###
POST http://localhost:3000/api/auth/authorize